## 11.4 释放资源

当在打开文件或者打开网络或数据库以后，这样的资源最终是不能够被Python语言进行自动释放的。  

需要程序员自行的编写代码进行释放。  

### 11.4.1 finally代码块  

try-except-finally语句语法如下：

    try:
        <可能会抛出异常的语句>
    except [异常类型1]:
        <处理异常>
    except [异常类型2]:
        ……
    except [异常类型n]:
        <处理异常>
    finally:
        <释放资源>

总体来说不管是出现异常情况还是正常结束的程序运行，最终都会运行“finally”模块。因此就可以将“finally”代码块作为释放资源的模块。  

例如：  

    import datetime as dt
    import traceback as tb

    def read_data_from_file(filename):
        try:
            file = open(filename)
            in_date = file.read(filename)
            in_date = in_date.strip()  # 取出前后空白
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        except ValueError:
            print('处理ValueError异常')
        except FileNotFoundError:
            print('处理FileNotFoundError异常')
        except OSError:
            print('处理OSError异常')
        finally:
            # 关闭文件，释放资源
            file.close()

    print('日期 = {0}'.format(read_data_from_file(readme.txt)

## 11.4.2 else代码块

指程序正常执行，完成之后会走“else”代码块。当出现问题、出现异常、出现“return”等等，在这些情况下就不会走“else”代码块。  

“else”的语法结构如下：  

    try:
        <可能会抛出异常的语句>
    except [异常类型1]:
        <处理异常>
    except [异常类型2]:
        ……
    except [异常类型n]:
        <处理异常>
    else:
        <执行语句>
    finally:
        <释放资源>

## 11.4.3 With as 代码块自动资源管理

例如：  

    import datetime as dt
    import traceback as tb

    def read_data_from_file(filename):
        try:
            with open(filename) as file:
                in_date = file.read(filename)
        
            in_date = in_date.strip()  # 取出前后空白
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        except ValueError:
            print('处理ValueError异常')
        except FileNotFoundError:
            print('处理FileNotFoundError异常')

    print('日期 = {0}'.format(read_data_from_file(readme.txt)))

打开文件的流程放到with代码块中，在with代码块中主要需要做的是读取文件的内容。With代码块结束之后，资源就自动释放了，因此也不需要使用finally代码块以及释放资源了。通过with as即可自动管理资源。
