## 11.6 显式抛出异常  

由于异常的产生都是由系统产生的异常对象，并最终被捕获进行异常的处理。而由程序员手工的抛出异常的情况则被称为显式抛出异常。  
系统抛出的异常与显式抛出的异常的处理方式都是一样的。  

显式抛出异常格式如下：  

    raise BaseException或其子类的实例。

例如：  

    import datetime as dt
    import traceback as tb

    def read_data_from_file(filename):
        try:
            with open(filename) as file:
                in_date = file.read(filename)

            in_date = in_date.strip()  # 取出前后空白
            date = dt.datetime.strptime(in_date, '%Y-%m-%d')
            return date
        except ValueError:
            #print('处理ValueError异常')
            raise MyException('处理ValueError异常')
        except FileNotFoundError:
            #print('处理FileNotFoundError异常')
            raise MyException('处理FileNotFoundError异常')

在此，并没有对捕获的异常进行处理，而是采用了显式的抛出了异常。
